# Generated by Django 5.0.7 on 2024-11-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mainoneleft_mainoneright_mainonetop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTwoLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('but_name', models.CharField(max_length=40)),
                ('but_adress', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MainTwoRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
